using System.ComponentModel;
using System.Diagnostics;
using System.Text;
using DevPilot.Application.Executions.Dtos;

namespace DevPilot.Infrastructure.Executions;

public static class VerificationSideEffectCleaner
{
    private static readonly TimeSpan DefaultGitTimeout = TimeSpan.FromSeconds(30);

    public sealed record StatusEntry(string Path, string? OldPath, string StatusCode, string ChangeType);

    /// <summary>
    /// Purges all verification-generated artifacts and reverts unmanaged modifications
    /// while strictly preserving files intentionally modified or created by the task (generation or repair).
    /// </summary>
    public static async Task<IReadOnlyList<string>> PurgeSideEffectsAsync(
        string workspacePath,
        IReadOnlyCollection<string> authoritativeModifiedFiles,
        CancellationToken cancellationToken = default)
    {
        if (string.IsNullOrWhiteSpace(workspacePath) || !Directory.Exists(workspacePath))
        {
            return Array.Empty<string>();
        }

        var fullWorkspacePath = Path.GetFullPath(workspacePath);
        var normalizedAuthoritative = authoritativeModifiedFiles
            .Where(f => !string.IsNullOrWhiteSpace(f))
            .Select(NormalizePath)
            .ToHashSet(StringComparer.OrdinalIgnoreCase);

        var statusResult = await RunGitCommandAsync(
            fullWorkspacePath,
            cancellationToken,
            "status", "--porcelain=v1", "-z", "--untracked-files=all").ConfigureAwait(false);

        if (!statusResult.IsSuccess || statusResult.RawBytes.Length == 0)
        {
            return Array.Empty<string>();
        }

        var entries = ParseStatusPorcelainZ(statusResult.RawBytes);
        var purgedPaths = new List<string>();

        foreach (var entry in entries)
        {
            var normPath = NormalizePath(entry.Path);
            var normOldPath = !string.IsNullOrEmpty(entry.OldPath) ? NormalizePath(entry.OldPath) : null;

            // Preserve any file intentionally changed or added by DeveloperAgent or repair
            if (normalizedAuthoritative.Contains(normPath) ||
                (normOldPath != null && normalizedAuthoritative.Contains(normOldPath)))
            {
                continue;
            }

            var fullFilePath = Path.Combine(fullWorkspacePath, entry.Path.Replace('/', Path.DirectorySeparatorChar));

            if (entry.StatusCode == "??" || entry.StatusCode == "A " || entry.StatusCode == "AM")
            {
                // New untracked artifact generated by build/test tools -> delete from disk
                try
                {
                    if (File.Exists(fullFilePath))
                    {
                        File.Delete(fullFilePath);
                        purgedPaths.Add(entry.Path);
                        TryDeleteEmptyParentDirectories(Path.GetDirectoryName(fullFilePath), fullWorkspacePath);
                    }
                    else if (Directory.Exists(fullFilePath))
                    {
                        Directory.Delete(fullFilePath, recursive: true);
                        purgedPaths.Add(entry.Path);
                        TryDeleteEmptyParentDirectories(Path.GetDirectoryName(fullFilePath), fullWorkspacePath);
                    }
                }
                catch
                {
                    // Fallback to git clean if file is locked or in nested directory
                }
            }
            else
            {
                // Tracked file modified solely by verification tools -> revert to HEAD
                await RunGitCommandAsync(fullWorkspacePath, cancellationToken, "checkout", "HEAD", "--", entry.Path).ConfigureAwait(false);
                purgedPaths.Add(entry.Path);
            }
        }

        return purgedPaths;
    }

    /// <summary>
    /// Pure function that partitions current status entries into preserved authoritative changes and verification side effects.
    /// </summary>
    public static (IReadOnlyList<StatusEntry> Preserved, IReadOnlyList<StatusEntry> SideEffects) ClassifyStatusEntries(
        IReadOnlyList<StatusEntry> currentEntries,
        IReadOnlyCollection<string> authoritativeModifiedFiles)
    {
        var normalizedAuthoritative = authoritativeModifiedFiles
            .Where(f => !string.IsNullOrWhiteSpace(f))
            .Select(NormalizePath)
            .ToHashSet(StringComparer.OrdinalIgnoreCase);

        var preserved = new List<StatusEntry>();
        var sideEffects = new List<StatusEntry>();

        foreach (var entry in currentEntries)
        {
            var normPath = NormalizePath(entry.Path);
            var normOldPath = !string.IsNullOrEmpty(entry.OldPath) ? NormalizePath(entry.OldPath) : null;

            if (normalizedAuthoritative.Contains(normPath) ||
                (normOldPath != null && normalizedAuthoritative.Contains(normOldPath)))
            {
                preserved.Add(entry);
            }
            else
            {
                sideEffects.Add(entry);
            }
        }

        return (preserved, sideEffects);
    }

    public static List<StatusEntry> ParseStatusPorcelainZ(byte[] rawBytes)
    {
        var entries = new List<StatusEntry>();
        if (rawBytes == null || rawBytes.Length == 0)
        {
            return entries;
        }

        var tokens = SplitByNul(rawBytes);
        var index = 0;

        while (index < tokens.Count)
        {
            var token = tokens[index];
            index++;

            if (token.Length < 3)
            {
                continue;
            }

            var x = token[0];
            var y = token[1];
            var path = token.Substring(3);

            if (string.IsNullOrWhiteSpace(path))
            {
                continue;
            }

            string? oldPath = null;
            if (x == 'R' || y == 'R' || x == 'C' || y == 'C')
            {
                if (index < tokens.Count)
                {
                    oldPath = tokens[index];
                    index++;
                }
            }

            var statusCode = $"{x}{y}";
            var changeType = DetermineChangeType(x, y);
            entries.Add(new StatusEntry(path, oldPath, statusCode, changeType));
        }

        return entries;
    }

    public static string NormalizePath(string path)
    {
        if (string.IsNullOrWhiteSpace(path)) return string.Empty;
        var p = path.Replace('\\', '/').Trim();
        while (p.StartsWith("./", StringComparison.Ordinal))
        {
            p = p.Substring(2);
        }
        return p.TrimStart('/');
    }

    private static string DetermineChangeType(char x, char y)
    {
        if (x == 'R' || y == 'R') return "Renamed";
        if (x == 'C' || y == 'C') return "Copied";
        if (x == '?' && y == '?') return "Added";
        if (x == 'A' || y == 'A') return "Added";
        if (x == 'D' || y == 'D') return "Deleted";
        if (x == 'M' || y == 'M') return "Modified";

        return $"{x}{y}".Trim();
    }

    private static List<string> SplitByNul(byte[] bytes)
    {
        var result = new List<string>();
        var start = 0;

        for (var i = 0; i < bytes.Length; i++)
        {
            if (bytes[i] == 0)
            {
                if (i > start)
                {
                    var token = Encoding.UTF8.GetString(bytes, start, i - start);
                    result.Add(token);
                }
                else if (i == start)
                {
                    result.Add("");
                }
                start = i + 1;
            }
        }

        if (start < bytes.Length)
        {
            var token = Encoding.UTF8.GetString(bytes, start, bytes.Length - start);
            result.Add(token);
        }

        return result;
    }

    private static void TryDeleteEmptyParentDirectories(string? dirPath, string workspaceRoot)
    {
        var current = dirPath;
        while (!string.IsNullOrEmpty(current) &&
               !string.Equals(Path.GetFullPath(current), Path.GetFullPath(workspaceRoot), StringComparison.OrdinalIgnoreCase) &&
               current.StartsWith(workspaceRoot, StringComparison.OrdinalIgnoreCase))
        {
            try
            {
                if (Directory.Exists(current) && !Directory.EnumerateFileSystemEntries(current).Any())
                {
                    Directory.Delete(current, false);
                    current = Path.GetDirectoryName(current);
                }
                else
                {
                    break;
                }
            }
            catch
            {
                break;
            }
        }
    }

    private static async Task<GitCommandResult> RunGitCommandAsync(
        string workingDirectory,
        CancellationToken cancellationToken,
        params string[] arguments)
    {
        using var timeoutCts = new CancellationTokenSource(DefaultGitTimeout);
        using var linkedCts = CancellationTokenSource.CreateLinkedTokenSource(cancellationToken, timeoutCts.Token);

        var psi = new ProcessStartInfo
        {
            FileName = "git",
            RedirectStandardOutput = true,
            RedirectStandardError = true,
            UseShellExecute = false,
            CreateNoWindow = true,
            WorkingDirectory = workingDirectory
        };

        psi.ArgumentList.Add("-c");
        psi.ArgumentList.Add("safe.directory=*");

        foreach (var arg in arguments)
        {
            psi.ArgumentList.Add(arg);
        }

        using var process = new Process { StartInfo = psi };

        try
        {
            process.Start();
        }
        catch (Win32Exception ex)
        {
            return new GitCommandResult(false, Array.Empty<byte>(), "", $"Git executable not found: {ex.Message}");
        }

        using var msOut = new MemoryStream();
        var msOutTask = process.StandardOutput.BaseStream.CopyToAsync(msOut, linkedCts.Token);
        var errTask = process.StandardError.ReadToEndAsync();

        try
        {
            await process.WaitForExitAsync(linkedCts.Token).ConfigureAwait(false);
            await Task.WhenAll(msOutTask, errTask).ConfigureAwait(false);
        }
        catch (OperationCanceledException)
        {
            try
            {
                process.Kill(entireProcessTree: true);
            }
            catch
            {
                // Best-effort process kill
            }

            var message = timeoutCts.IsCancellationRequested
                ? "Git process timed out."
                : "Git operation was cancelled.";

            return new GitCommandResult(false, Array.Empty<byte>(), "", message);
        }

        var rawBytes = msOut.ToArray();
        var stdOutText = Encoding.UTF8.GetString(rawBytes);
        var stdErrText = await errTask.ConfigureAwait(false);

        return new GitCommandResult(process.ExitCode == 0, rawBytes, stdOutText, stdErrText);
    }

    private sealed record GitCommandResult(bool IsSuccess, byte[] RawBytes, string StdOut, string StdErr);
}
